name: CI-CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  AZURE_RG: RG1
  AZURE_SUBSCRIPTION: c6bc3979-b7f6-4d26-8372-5a3db8259a88
  AZURE_LOCATION: WestEurope

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      configuration: Release

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup .NET from global.json
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Display .NET information
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore U2U_GameStore.sln

      - name: Build
        run: >
          dotnet build U2U_GameStore.sln
          --no-restore
          --configuration ${{ env.configuration }}

      - name: Test
        run: >
          dotnet test U2U_GameStore.sln
          --no-build
          --configuration ${{ env.configuration }}
          --verbosity normal

      - name: Publish web application
        run: >
          dotnet publish
          src/U2U.GameStore.Web/U2U.GameStore.Web.csproj
          --no-restore
          --configuration ${{ env.configuration }}
          --output ${{ runner.temp }}/publish

      - name: Upload published application
        uses: actions/upload-artifact@v4
        with:
          name: gamestore-web
          path: ${{ runner.temp }}/publish
